### ISSUE TITLE
Error: Old release tag 

### ISSUE THREAD

**Issue by savya10** [amitsingh-007/next-release-tag#27] opened 2023-06-02 12:07 UTC
Hi,

I'm having an issue with generating a release tag for my package using v4.0.0 - the error message says `Error: Old release tag not found`.  This error also persists after an initial manual release of my package (release tag is v1.0.0), so the solution to Issue #8 doesn't fix it. 

This is the relevant part of my workflow at the moment:

```
      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: 'v'
          tag_template: 'yy.mm.i'
```

I'd greatly appreciate any help you could provide - thanks in advance!

**Comment by amitsingh-007** [comment] 2023-06-02 13:37
Thanks @savya10 for reporting the issue.
I just tried this with a new repository with no release at first, it gave the error(which is expected since this was a breaking change I introduced in v4 which requires an existing release tag in the repository. This is also documented in the readme).

After this, I created a new release with v1.0.0 and it worked.
Did you actually publish your release or was it made a pre-release or a draft release instead?

**Comment by savya10** [comment] 2023-06-02 13:42
Thanks for the quick response! It was a pre-release - I will try doing the full release and hopefully that will fix it.

**Comment by amitsingh-007** [comment] 2023-06-02 13:45
Okay. Please update here if it works with a full release and I will close this issue.

But that's a good point. I intentionally didn't fetch all the tags for the repository and instead fetched tag of the latest release only to process it quicker.
Maybe I will change the behaviour since people might not want to manually publish a release just to use an action.

**Comment by savya10** [comment] 2023-06-02 14:43
It works with the full release! Thanks for all the help 😄

**Comment by amitsingh-007** [comment] 2023-06-02 14:56
Closing as not a bug

**Closed by amitsingh-007** 2023-06-02 14:56 UTC
